apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet8-template
  title: Dotnet 8 Template
  description: Scaffold a new .NET 8 project
  tags:
    - dotnet
    - csharp
    - webapi
    - recommended
spec:
  owner: user:rfpolo5
  type: service

  parameters:
    - title: "Complete the form to create a new .NET 8 project"
      required:
        - name
        - description
        - system
      properties:
        name:
          type: string
          title: "Project Name"
          description: "The name of the project"
        description:
          type: string
          title: "Description"
          description: "A description for the component"
        owner:
          type: string
          title: "Owner"
          description: "The owner of the component"
        system:
          type: string
          title: "System"
          description:
